config/routes.rb
Blog::Application.routes.draw do

  resources :list_subscribers

  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    get 'signin' => 'devise/sessions#new', as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  scope 'a', module: 'admin', as: 'admin' do
    scope "blog" do
      resources :posts, except: [:show]
    end
    resources :comments, except: [:create, :new] do
      collection do
        delete 'destroy-batch' => "comments#destroy_batch", as: "destroy_batch"
      end
      member do
        put 'approve'
        put 'reject'
      end
    end
    resources :users, except: [:index, :new, :create, :destroy]
    get 'dashboard' => 'users#dashboard', as: 'root'
  end

  scope "/settings" do

  end

  get '/dashboard' => 'admin/users#dashboard', as: :user_root

  scope "blog" do
    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:create, :new]
    end
  end

  resources :subscribers, controller: 'list_subscribers', only: [:create, :new] do
    collection do
      post 'confirm'
      get 'confirm' # used by MailChimp to confirm
    end
  end

  # Static content
  get 'about' => 'content#about'
  get 'projects' => 'content#projects'
  get 'resume' => 'content#resume'

  # You can have the root of your site routed with "root"
  root :to => "content#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Rakismet::Model
  has_ancestry

  belongs_to :commentable, polymorphic: true, touch: true

  scope :published, -> { where(approved: true) }
  scope :unapproved, -> { where(approved: false) }

  rakismet_attrs :author => :name, :author_email => :email, :author_url => :site_url, :author_ip => :user_ip

  validates_presence_of :body, :email, :name
  validates_format_of :email,
    :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
    :message => "Invalid email format.",
    :if => "email.present?"

  before_create :check_for_spam

  def mark_as_ham!
    update_attribute(:approved, true)
    self.ham!
  end

  def mark_as_spam!
    update_attribute(:approved, false)
    self.spam!
  end

  def notify_other_commenters
    Mailer.notify_admin_and_author(self).deliver_now
    Mailer.comment_response(self, parent).deliver_now if !!parent && self.approved?
  end

  private

  def check_for_spam
    self.approved = !self.spam?
    true
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include PgSearch

  belongs_to :author, :class_name => "User"
  has_many :comments, as: :commentable, :dependent => :destroy

  attr_accessor :published_at_string

  extend FriendlyId
  friendly_id :title, use: :slugged

  acts_as_taggable

  scope :published, lambda { where('published_at <= ?', Time.now.utc) }
  scope :unpublished, lambda { where('published_at > ?', Time.now.utc) }

  mount_uploader :image, BlogImageUploader

  before_validation :format_published_at
  validates_presence_of :abstract, :body, :description, :title

  pg_search_scope :search,
    against: [:title, :abstract, :body],
    using: {
      tsearch: {
        dictionary: "english",
        :any_word => true
      },
      trigram: {}
    }

  def self.text_search(query)
    if query.present?
      search(query)
    else
      all
    end
  end

  def editable_by?(user)
    return false if user.nil?
    user.admin? or user.id == author_id
  end

  def is_commentable?
    is_commentable
  end

  def last_published?
    self == self.class.published.last
  end

  def published_at_formatted
    return "" if published_at.nil?
    published_at.strftime("%m/%d/%Y")
  end

  def published_date
    return "" if published_at.nil?
    published_at.strftime("%d %b %Y")
  end

  def published_status
    return "draft" if published_at.nil?
    published_at <= Time.now.utc ? "published" : "scheduled"
  end

  def should_generate_new_friendly_id?
    new_record?
  end

  def tag_list_sorted
    tag_list.map{ |t| t }.sort
  end

  private

  def format_published_at
    return true if self.published_at
    return self.published_at = nil if self.published_at_string.nil? || self.published_at_string.empty?
    unless (published_at_formatted == published_at_string)
      date_string = "#{self.published_at_string} 06:00 -0700"
      self.published_at = DateTime.strptime(date_string, '%m/%d/%Y %H:%M %z')
    end
  end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < AdminController
  before_action :load_comment, except: [:destroy_batch, :index]
  helper_method :sort_column, :sort_direction

  # GET /a/comments
  def index
    load_comments
  end

  # GET /a/comments/1/edit
  def edit
  end

  # PATCH/PUT /a/comments/1
  def update
    if @comment.update(params[:comment])
      redirect_to admin_comments_path, notice: 'Comment was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # PATCH/PUT /a/comments/1/approve
  def approve
    @comment.mark_as_ham!
    redirect_to admin_comments_path, notice: "Comment has been approved."
  end

  # PATCH/PUT /a/comments/1/reject
  def reject
    @comment.mark_as_spam!
    redirect_to admin_comments_path, notice: "Comment has been rejected."
  end

  # DELETE /a/comments/1
  def destroy
    @comment.destroy
    redirect_to admin_comments_path, notice: 'Comment was successfully destroyed.'
  end

  def destroy_batch
    Comment.destroy(params[:comment_ids])
    redirect_to admin_comments_path, notice: "Successfully destroyed comments."
  end

  private

  def load_comment
    @comment ||= comment_scope.find(params[:id])
  end

  def load_comments
    query         = Sanitize.clean(params[:search])
    page          = params[:page] || 1
    sort_order    = Sanitize.clean(sort_column + " " + sort_direction)
    @comments ||= comment_scope.paginate(:page => page, :per_page => 10).reorder(sort_order)
  end

  def comment_scope
    Comment.all
  end

  def sort_column
    sort      = Sanitize.clean(params[:sort])
    Comment.column_names.include?(sort) ? sort : "created_at"
  end

  def sort_direction
    direction = Sanitize.clean(params[:direction])
    %w[asc desc].include?(direction) ? direction : "desc"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  prepend_before_action :merge_params, only: [:create, :update]
  prepend_before_action :load_commentable, only: [:new, :create, :edit, :update]
  prepend_before_action :authenticate_user!, :except => [:index, :new, :create]

  # GET /comments/new
  def new
    @comment = Comment.new(parent_id: params[:parent_id])
  end

  # POST /comments
  def create
    @comment = Comment.new(params[:comment])

    if @comment.save
      unless @comment.approved?
        flash[:error] = "Unfortunately this comment is considered spam by Akismet. " +
                      "It will show up once it has been approved by the administrator."
      end
    end

    respond_to do |format|
      format.html do
        if @comment.errors.present?
          render :new
        else
          redirect_to @commentable, :view => "comments"
        end
      end
      format.js
    end

  end

  private

    def merge_params
      params[:comment].merge!({
        user_ip: request.remote_ip,
        user_agent: request.env['HTTP_USER_AGENT'],
        referrer: request.env['HTTP_REFERER'],
        approved: false,
        commentable_id: @commentable.id,
        commentable_type: @commentable.class.to_s
      })
    end

    def load_commentable
      resource, id = request.path.split('/')[2, 3] # /blog/article/1
      @commentable = resource.singularize.classify.constantize.friendly.find(id)
    end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

  def append_new_comment(comment)
    render(comment) + content_tag(:div, "", :class => "nested_comments")
  end

  def button_for(comment)
    if comment.approved?
      link_to raw("<i class='icon-thumbs-down icon-white'></i>"), reject_admin_comment_path(comment), class: "btn btn-sm btn-danger",
        data: { confirm: "Are you sure you want to mark the comment as spam?" }, method: :put, title: "Reject comment."
    else
      link_to raw("<i class='icon-thumbs-up'></i>"), approve_admin_comment_path(comment), class: "btn btn-sm btn-default",
        data: { confirm: "Are you sure you want to approve the comment?" }, method: :put, title: "Approve comment."
    end
  end

  def fix_url(url)
    if url =~ /^https?\:\/\//
      url
    else
      "http://#{url}"
    end
  end

  def format_comment(comment)
    markdown_render(keep_spaces_at_beginning(h(comment.body)))
  end

  def keep_spaces_at_beginning(content)
    content.split("\n").map do |line|
      line.sub(/^ +/) do |spaces|
        '&nbsp;' * spaces.length
      end
    end.join("\n")
  end

  def marked_as_spam(comment)
    content_tag(:div, class: "alert alert-block alert-warn") do
      content_tag(:h4, "Unfortunately this comment is considered spam by Akismet. ", class: "alert-heading") +
      content_tag(:p, "It will show up once it has been approved by the administrator.")
    end
  end

  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
    end.join.html_safe
  end

end

app/views/admin/comments/_form.html.haml
= simple_form_for @comment, url: admin_comment_path(@comment), :html => { class: 'well' } do |f|
  - if @comment.errors.any?
    .alert.alert-block.alert-error
      %a.close{"data-dismiss" => "alert"} ×
      %h4.alert-heading Oh Snap!
      We found #{pluralize(@comment.errors.count, "problem")} with the form:
  = f.hidden_field :parent_id
  = f.input :name, :required => true
  = f.input :email, :required => true, :hint => 'Not published'
  = f.input :site_url
  = f.input :body, :label => "Comment", :as => :text, :input_html => {:class => 'span6', :rows => 10}
  .form-actions
    = f.submit "Update Comment", :class => "btn btn-primary"
    = link_to 'Back', admin_comments_path, class: "btn btn-small"

app/views/admin/comments/edit.html.haml
- content_for :title,  "Edit Comment"
= render :partial => "shared/page_title", locals: { :title => "Edit Comment" }

.container
  .row
    .col-sm-12
      = render 'form'

app/views/admin/comments/index.html.haml
- content_for :title,  "Comments"

.row
  .col-lg-12
    .box
      .box-header
        %h2
          %i.fa.fa-pencil
          = succeed "Blog Comments" do
            %span.break
        .box-icon
      .box-content.clearfix
        = form_for destroy_batch_admin_comments_path, method: :delete do
          %table.table.table-striped.table-bordered.bootstrap-datatable.datatable
            %thead
              %tr
                %th
                %th Commenter
                %th Comment
                %th User Info
                %th Approved?
                %th Actions
            %tbody
              - @comments.each do |comment|
                %tr{:class => comment.approved? ? '' : 'error'}
                  %td= check_box_tag "comment_ids[]", comment.id
                  %td
                    = comment.name
                    %br/
                    = comment.email
                    %br/
                    = comment.site_url
                  %td= format_comment(comment)
                  %td
                    = comment.user_ip
                    %br/
                    = comment.user_agent
                    %br/
                    = comment.referrer
                  %td= comment.approved
                  %td{width:"10%"}
                    .btn-group
                      = button_for(comment)
                      = link_to raw("<i class='icon-pencil'></i>"), edit_admin_comment_path(comment), class: "btn btn-sm btn-default"
                      = link_to raw("<i class='icon-trash icon-white'></i>"), admin_comment_path(comment), class: "btn btn-sm btn-danger",
          data: { confirm: "Are you sure you want to perminately delete the comment?" }, method: :delete, title: "Delete comment."
        %p= submit_tag "Destroy Checked", class: 'btn btn-danger'
        %section
          = paginate(@comments)