config/routes.rb
Blog::Application.routes.draw do

  resources :list_subscribers

  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    get 'signin' => 'devise/sessions#new', as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  scope 'a', module: 'admin', as: 'admin' do
    scope "blog" do
      resources :posts, except: [:show]
    end
    resources :comments, except: [:create, :new] do
      collection do
        delete 'destroy-batch' => "comments#destroy_batch", as: "destroy_batch"
      end
      member do
        put 'approve'
        put 'reject'
      end
    end
    resources :users, except: [:index, :new, :create, :destroy]
    get 'dashboard' => 'users#dashboard', as: 'root'
  end

  scope "/settings" do

  end

  get '/dashboard' => 'admin/users#dashboard', as: :user_root

  scope "blog" do
    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:create, :new]
    end
  end

  resources :subscribers, controller: 'list_subscribers', only: [:create, :new] do
    collection do
      post 'confirm'
      get 'confirm' # used by MailChimp to confirm
    end
  end

  # Static content
  get 'about' => 'content#about'
  get 'projects' => 'content#projects'
  get 'resume' => 'content#resume'

  # You can have the root of your site routed with "root"
  root :to => "content#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Rakismet::Model
  has_ancestry

  belongs_to :commentable, polymorphic: true, touch: true

  scope :published, -> { where(approved: true) }
  scope :unapproved, -> { where(approved: false) }

  rakismet_attrs :author => :name, :author_email => :email, :author_url => :site_url, :author_ip => :user_ip

  validates_presence_of :body, :email, :name
  validates_format_of :email,
    :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
    :message => "Invalid email format.",
    :if => "email.present?"

  before_create :check_for_spam

  def mark_as_ham!
    update_attribute(:approved, true)
    self.ham!
  end

  def mark_as_spam!
    update_attribute(:approved, false)
    self.spam!
  end

  def notify_other_commenters
    Mailer.notify_admin_and_author(self).deliver_now
    Mailer.comment_response(self, parent).deliver_now if !!parent && self.approved?
  end

  private

  def check_for_spam
    self.approved = !self.spam?
    true
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < AdminController
  before_action :load_comment, except: [:destroy_batch, :index]
  helper_method :sort_column, :sort_direction

  # GET /a/comments
  def index
    load_comments
  end

  # GET /a/comments/1/edit
  def edit
  end

  # PATCH/PUT /a/comments/1
  def update
    if @comment.update(params[:comment])
      redirect_to admin_comments_path, notice: 'Comment was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # PATCH/PUT /a/comments/1/approve
  def approve
    @comment.mark_as_ham!
    redirect_to admin_comments_path, notice: "Comment has been approved."
  end

  # PATCH/PUT /a/comments/1/reject
  def reject
    @comment.mark_as_spam!
    redirect_to admin_comments_path, notice: "Comment has been rejected."
  end

  # DELETE /a/comments/1
  def destroy
    @comment.destroy
    redirect_to admin_comments_path, notice: 'Comment was successfully destroyed.'
  end

  def destroy_batch
    Comment.destroy(params[:comment_ids])
    redirect_to admin_comments_path, notice: "Successfully destroyed comments."
  end

  private

  def load_comment
    @comment ||= comment_scope.find(params[:id])
  end

  def load_comments
    query         = Sanitize.clean(params[:search])
    page          = params[:page] || 1
    sort_order    = Sanitize.clean(sort_column + " " + sort_direction)
    @comments ||= comment_scope.paginate(:page => page, :per_page => 10).reorder(sort_order)
  end

  def comment_scope
    Comment.all
  end

  def sort_column
    sort      = Sanitize.clean(params[:sort])
    Comment.column_names.include?(sort) ? sort : "created_at"
  end

  def sort_direction
    direction = Sanitize.clean(params[:direction])
    %w[asc desc].include?(direction) ? direction : "desc"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  prepend_before_action :merge_params, only: [:create, :update]
  prepend_before_action :load_commentable, only: [:new, :create, :edit, :update]
  prepend_before_action :authenticate_user!, :except => [:index, :new, :create]

  # GET /comments/new
  def new
    @comment = Comment.new(parent_id: params[:parent_id])
  end

  # POST /comments
  def create
    @comment = Comment.new(params[:comment])

    if @comment.save
      unless @comment.approved?
        flash[:error] = "Unfortunately this comment is considered spam by Akismet. " +
                      "It will show up once it has been approved by the administrator."
      end
    end

    respond_to do |format|
      format.html do
        if @comment.errors.present?
          render :new
        else
          redirect_to @commentable, :view => "comments"
        end
      end
      format.js
    end

  end

  private

    def merge_params
      params[:comment].merge!({
        user_ip: request.remote_ip,
        user_agent: request.env['HTTP_USER_AGENT'],
        referrer: request.env['HTTP_REFERER'],
        approved: false,
        commentable_id: @commentable.id,
        commentable_type: @commentable.class.to_s
      })
    end

    def load_commentable
      resource, id = request.path.split('/')[2, 3] # /blog/article/1
      @commentable = resource.singularize.classify.constantize.friendly.find(id)
    end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper

  def append_new_comment(comment)
    render(comment) + content_tag(:div, "", :class => "nested_comments")
  end

  def button_for(comment)
    if comment.approved?
      link_to raw("<i class='icon-thumbs-down icon-white'></i>"), reject_admin_comment_path(comment), class: "btn btn-sm btn-danger",
        data: { confirm: "Are you sure you want to mark the comment as spam?" }, method: :put, title: "Reject comment."
    else
      link_to raw("<i class='icon-thumbs-up'></i>"), approve_admin_comment_path(comment), class: "btn btn-sm btn-default",
        data: { confirm: "Are you sure you want to approve the comment?" }, method: :put, title: "Approve comment."
    end
  end

  def fix_url(url)
    if url =~ /^https?\:\/\//
      url
    else
      "http://#{url}"
    end
  end

  def format_comment(comment)
    markdown_render(keep_spaces_at_beginning(h(comment.body)))
  end

  def keep_spaces_at_beginning(content)
    content.split("\n").map do |line|
      line.sub(/^ +/) do |spaces|
        '&nbsp;' * spaces.length
      end
    end.join("\n")
  end

  def marked_as_spam(comment)
    content_tag(:div, class: "alert alert-block alert-warn") do
      content_tag(:h4, "Unfortunately this comment is considered spam by Akismet. ", class: "alert-heading") +
      content_tag(:p, "It will show up once it has been approved by the administrator.")
    end
  end

  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
    end.join.html_safe
  end

end

app/views/comments/_comment.html.haml
= div_for comment do
  = image_tag gravatar_url(comment, 50), alt: "Avatar", class: "avatar img-polaroid"
  .main
    = render "comments/comment_headline", :comment => comment
    .comment_content
      = format_comment(comment)
      .actions
        = link_to raw('<i class="mini-ico-share-alt"></i> Reply'), new_polymorphic_path([@commentable, Comment.new], :parent_id => comment), class: "btn btn-mini", remote: true
  .clear

app/views/comments/_comment_headline.html.haml
.headline
  - if comment.new_record?
    %span.position New comment as
  %span.name
    - if comment.site_url
      = link_to comment.name, fix_url(comment.site_url), :rel => "nofollow"
    - else
      = comment.name
    - if params[:controller] != "posts"
      on #{link_to comment.commentable.title, posts_path(comment.commentable, :view => "comments", :anchor => "comment_#{comment.id}")}
  %span.pull-right
    = time_ago_in_words comment.created_at
    ago

app/views/comments/_form.html.haml
= simple_form_for [@commentable, @comment], :html => { id: nil, class: 'well form-horizontal', remote: true } do |f|
  - if @comment.errors.any?
    .alert.alert-block.alert-error
      %a.close{"data-dismiss" => "alert"} ×
      %h4.alert-heading Oh Snap!
      We found #{pluralize(@comment.errors.count, "problem")} with the form:
  = f.hidden_field :parent_id
  .control-group.required
    = f.label :name, required: true
    .controls
      = f.input_field :name
  .control-group.required
    = f.label :email, required: true
    .controls
      = f.input_field :email, hint: 'Not published'
  .control-group
    = f.label :site_url
    .controls
      = f.input_field :site_url
  .control-group
    = f.label :body, label: "Comment"
    .controls
      = f.input_field :body, as: :text, class: 'span6', rows: 10
  .form-actions
    = f.submit "Submit Comment", :class => "btn btn-primary"

app/views/comments/create.js.erb
<% if @comment.parent_id.present? %>
  var form_container    = $("#<%= dom_id(@comment.parent) %>").next(".nested_comments");
  var comment_container = $("#<%= dom_id(@comment.parent) %>").next(".nested_comments");
<% else %>
  var form_container    = $("#comments");
  var comment_container = $("#comments .comments");
<% end %>
<% if @comment.errors.present? %>
  $(".alert.alert-block.alert-error").remove();
  form_container.find("form").prepend("<%= j error_messages_for(@comment) %>");
<% else %>
  $(".nested_comments form, .alert.alert-block.alert-warn").remove();
  $("#comment_form_prime form")[0].reset();
  <% if @comment.approved? %>
    comment_container.append("<%= j append_new_comment(@comment) %>");
  <% else %>
    comment_container.append("<%= j marked_as_spam(@comment) %>");
  <% end %>
<% end %>

app/views/comments/edit.html.haml
%h1 Editing comment
= render 'form'
= link_to 'Show', @comment
|
\#{link_to 'Back', comments_path}

app/views/comments/new.html.haml
- content_for :title,  "New Comment"
= render partial: "shared/page_title", locals: {title: "New Comment", icon_class: "ico-comments"}
= render 'form'

app/views/comments/new.js.erb
if ($("#comment_<%= params[:parent_id] %>").next(".nested_comments").children("#new_comment").length == 0) {
  $("#comment_<%= params[:parent_id] %>").next(".nested_comments").prepend("<%= escape_javascript render("form") %>");
  $("#comment_<%= params[:parent_id] %>").next(".nested_comments").find("#comment_content")[0].focus();
}

app/views/comments/show.html.haml
%p#notice= notice
%p
  %strong Body:
  = @comment.body
%p
  %strong Email:
  = @comment.email
%p
  %strong Site url:
  = @comment.site_url
%p
  %strong User ip:
  = @comment.user_ip
%p
  %strong User agent:
  = @comment.user_agent
%p
  %strong Referrer:
  = @comment.referrer
%p
  %strong Approved:
  = @comment.approved
= link_to 'Edit', edit_comment_path(@comment)
|
\#{link_to 'Back', comments_path}