config/routes.rb
Blog::Application.routes.draw do

  resources :list_subscribers

  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    get 'signin' => 'devise/sessions#new', as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  scope 'a', module: 'admin', as: 'admin' do
    scope "blog" do
      resources :posts, except: [:show]
    end
    resources :comments, except: [:create, :new] do
      collection do
        delete 'destroy-batch' => "comments#destroy_batch", as: "destroy_batch"
      end
      member do
        put 'approve'
        put 'reject'
      end
    end
    resources :users, except: [:index, :new, :create, :destroy]
    get 'dashboard' => 'users#dashboard', as: 'root'
  end

  scope "/settings" do

  end

  get '/dashboard' => 'admin/users#dashboard', as: :user_root

  scope "blog" do
    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:create, :new]
    end
  end

  resources :subscribers, controller: 'list_subscribers', only: [:create, :new] do
    collection do
      post 'confirm'
      get 'confirm' # used by MailChimp to confirm
    end
  end

  # Static content
  get 'about' => 'content#about'
  get 'projects' => 'content#projects'
  get 'resume' => 'content#resume'

  # You can have the root of your site routed with "root"
  root :to => "content#index"

end

app/views/shared/_admin_page_title.html.haml
- content_for :content_top do
  .pg-opt.pin
    .container
      .row
        .col-md-6
          %h1= title

app/views/shared/_footer_bottom.html.haml
#footer-menu
  .container
    .row
      .span11
        #footer-menu-logo
          = link_to root_path, :class => "brand" do
            The Wayward
            %span Traveller
      .span1
        #footer-menu-back-to-top
          %a{href: "#"}
#copyright
  .container
    .span12
      %p © 2012 – Jeremy Ward – All Rights Reserved

app/views/shared/_footer_top.html.haml
#footer
  .container
    .row
      .span4
        %h3 The Gist
        :markdown
          I'm an adventure-seeking problem solver, creator of [Fitrme](https://fitrme.com), and brewer of beer. I write in cursive, listen to books, and delight in meaningful moments.
        %p
          %i.mini-ico-map-marker.mini-white
          Portland, OR, USA
        %p
          %i.ico-z-iphone
          If you know me, you probably have it.
        %p
          %i.mini-ico-envelope.mini-white
          Get in touch with me here.
      .span4
      / start: Mailing list?
      .span4
        %h3 Find Me On
        %ul.social-bookmarks.tooltips
          %li.github= link_to "Jeremy Ward on Github", 'https://github.com/jrmyward', rel: 'tooltip', title: 'Github'
          %li.googleplus= link_to "Jeremy Ward on Google Plus", 'https://plus.google.com/106353175482876519782', rel: 'tooltip', title: 'Google Plus'
          %li.linkedin= link_to "Jeremy Ward on LinkedIn", 'http://www.linkedin.com/in/jrmyward', rel: 'tooltip', title: 'LinkedIn'
          %li.rss= link_to "RSS", posts_url(format: "atom"), rel: 'tooltip', title: 'RSS'
          %li.skype= link_to "Jeremy Ward on Skype", '#', rel: 'tooltip', title: 'Skype'
          %li.twitter= link_to "Jeremy Ward on Twitter", 'https://twitter.com/jrmyward', rel: 'tooltip', title: 'Twitter'

app/views/shared/_header.html.haml
%header
  .container
    .navbar
      .navbar-inner
        %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to root_path, :class => "brand" do
          %i.ico-compass.ico-color.circle
          - if browser.mobile?
            Wayward
            %span Traveler
          - else
            The Wayward
            %span Traveler
        .nav-collapse.collapse
          %ul.nav
            - if user_signed_in? and (current_user.author? or current_user.admin?)
              %li= nav_link "Admin Dashboard", admin_root_path
            - else
              %li= nav_link "Blog", posts_path, /^\/blog/

app/views/shared/_header_admin.html.haml
%header.navbar
  .container
    %button.navbar-toggle{"data-target" => ".sidebar-nav.nav-collapse", "data-toggle" => "collapse", type: "button"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a#main-menu-toggle.hidden-xs.open
      %i.fa.fa-bars
    = link_to admin_root_path, title: "Reflections and Duty", class: "navbar-brand col-md-2 col-sm-1 col-xs-2" do
      Traveller
    .nav-no-collapse.header-nav
      %ul.nav.navbar-nav.pull-right
        - if current_user
          = render "shared/user_links"

app/views/shared/_layout_meta.html.haml
/ start: Meta
%meta{charset: "utf-8"}/
= csrf_meta_tags
%title= content_for?(:title) ? "#{yield(:title)} | The Wayward Traveller" : "Jeremy Ward | The Wayward Traveller"
%meta{content: content_for?(:meta_author) ? "#{yield(:meta_author)}" : "Jeremy Ward", name: "author"}/
%meta{content: content_for?(:description) ? "#{yield(:description)}" : "", name: "description"}/
= auto_discovery_link_tag(:atom, posts_url(format: "atom"))
/ start: Mobile Specific
%meta{content: "width=device-width, initial-scale=1, maximum-scale=1", name: "viewport"}/
/ start: Facebook Open Graph
%meta{content: content_for?(:title) ? "#{yield(:title)} | The Wayward Traveller" : "Jeremy Ward | The Wayward Traveller", property: "og:title"}/
%meta{content: content_for?(:description) ? "#{yield(:description)}" : "", property: "og:description"}/
%meta{content: content_for?(:og_type) ? "#{yield(:og_type)}" : "", property: "og:type"}/
%meta{content: "Jeremy Ward | The Wayward Traveller", property: "og:site_name"}/
%meta{content: content_for?(:og_url) ? "#{yield(:og_url)}" : "http://jrmyward.com", property: "og:url"}/
%meta{content: content_for?(:og_image) ? "#{yield(:og_image)}" : "#{image_url 'old_salmon_creek_trail.jpg'}", property: "og:image"}/
/ end: Facebook Open Graph
/ start: Twitter Card
%meta{content: "summary", name: "twitter:card"}/
%meta{content: "@jrmyward", name: "twitter:site"}/
%meta{content: content_for?(:title) ? "#{yield(:title)} | The Wayward Traveller" : "Jeremy Ward | The Wayward Traveller", name: "twitter:title"}/
%meta{content: content_for?(:description) ? "#{yield(:description)}" : "", name: "twitter:description"}/
%meta{content: content_for?(:og_image) ? "#{yield(:og_image)}" : "#{image_url 'old_salmon_creek_trail.jpg'}", name: "twitter:image:src"}/
%meta{content: content_for?(:meta_twitter_creator) ? "#{yield(:meta_twitter_creator)}" : "@jrmyward", name: "twitter:creator"}/
/ end: Twitter Card
%link{href: content_for?(:canonical) ? "#{yield(:canonical)}" : "#{request.original_url}", rel: "canonical"}/

app/views/shared/_nav_left.html.haml
#sidebar-left.col-lg-2.col-sm-1
  .sidebar-nav.nav-collapse.collapse.navbar-collapse
    %ul.nav.main-menu
      = render 'shared/nav_left_users'

  = link_to raw("<i class='fa fa-angle-double-left'></i>"), "#", id: "main-menu-min", class: "full visible-md visible-lg"

app/views/shared/_nav_left_users.html.haml
= admin_link_to("Dashboard", admin_root_path, "fa fa-bar-chart-o")

- if current_user.admin?
  %li
    = admin_link_to_dropdown "Blog", "glyphicons blog"
    %ul
      = admin_link_to("Posts", admin_posts_path, "glyphicons blog", "submenu")
      = admin_link_to("New Post", new_admin_post_path, "glyphicons blog", "submenu")
  %li
    = admin_link_to("Comments", admin_comments_path, "icon-comments")

app/views/shared/_page_title.html.haml
- content_for :content_top do
  #page-title
    #page-title-inner
      .container
        %h1
          %i{class: icon_class}
          = title

app/views/shared/_page_title_hero.html.haml
- content_for :content_top do
  #page-title.page-title-hero
    #page-title-inner
      .container
        %h1
          %i{class: icon_class}
          = title

app/views/shared/_user_links.html.haml
%li.dropdown
  = link_to '#', data: { toggle: "dropdown" }, class: "btn account dropdown-toggle"  do
    .avatar
      = image_tag gravatar_url(current_user, 64)
    .user
      %span.hello Welcome!
      %span.name= current_user.full_name
  %ul.dropdown-menu
    %li= link_to raw('<i class="icon-user"></i> Edit Profile'), edit_admin_user_path(current_user)
    %li.divider
    %li= link_to raw('<i class="icon-off"></i> Sign Out'), destroy_user_session_path, :method => :delete