config/routes.rb
Blog::Application.routes.draw do

  resources :list_subscribers

  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    get 'signin' => 'devise/sessions#new', as: :new_user_session
    post 'signin' => 'devise/sessions#create', as: :user_session
    delete 'signout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  scope 'a', module: 'admin', as: 'admin' do
    scope "blog" do
      resources :posts, except: [:show]
    end
    resources :comments, except: [:create, :new] do
      collection do
        delete 'destroy-batch' => "comments#destroy_batch", as: "destroy_batch"
      end
      member do
        put 'approve'
        put 'reject'
      end
    end
    resources :users, except: [:index, :new, :create, :destroy]
    get 'dashboard' => 'users#dashboard', as: 'root'
  end

  scope "/settings" do

  end

  get '/dashboard' => 'admin/users#dashboard', as: :user_root

  scope "blog" do
    get 'tags/:tag', to: 'posts#index', as: :tag
    resources :posts, only: [:index, :show] do
      resources :comments, only: [:create, :new]
    end
  end

  resources :subscribers, controller: 'list_subscribers', only: [:create, :new] do
    collection do
      post 'confirm'
      get 'confirm' # used by MailChimp to confirm
    end
  end

  # Static content
  get 'about' => 'content#about'
  get 'projects' => 'content#projects'
  get 'resume' => 'content#resume'

  # You can have the root of your site routed with "root"
  root :to => "content#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  include PgSearch

  belongs_to :author, :class_name => "User"
  has_many :comments, as: :commentable, :dependent => :destroy

  attr_accessor :published_at_string

  extend FriendlyId
  friendly_id :title, use: :slugged

  acts_as_taggable

  scope :published, lambda { where('published_at <= ?', Time.now.utc) }
  scope :unpublished, lambda { where('published_at > ?', Time.now.utc) }

  mount_uploader :image, BlogImageUploader

  before_validation :format_published_at
  validates_presence_of :abstract, :body, :description, :title

  pg_search_scope :search,
    against: [:title, :abstract, :body],
    using: {
      tsearch: {
        dictionary: "english",
        :any_word => true
      },
      trigram: {}
    }

  def self.text_search(query)
    if query.present?
      search(query)
    else
      all
    end
  end

  def editable_by?(user)
    return false if user.nil?
    user.admin? or user.id == author_id
  end

  def is_commentable?
    is_commentable
  end

  def last_published?
    self == self.class.published.last
  end

  def published_at_formatted
    return "" if published_at.nil?
    published_at.strftime("%m/%d/%Y")
  end

  def published_date
    return "" if published_at.nil?
    published_at.strftime("%d %b %Y")
  end

  def published_status
    return "draft" if published_at.nil?
    published_at <= Time.now.utc ? "published" : "scheduled"
  end

  def should_generate_new_friendly_id?
    new_record?
  end

  def tag_list_sorted
    tag_list.map{ |t| t }.sort
  end

  private

  def format_published_at
    return true if self.published_at
    return self.published_at = nil if self.published_at_string.nil? || self.published_at_string.empty?
    unless (published_at_formatted == published_at_string)
      date_string = "#{self.published_at_string} 06:00 -0700"
      self.published_at = DateTime.strptime(date_string, '%m/%d/%Y %H:%M %z')
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  before_action :load_post, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  respond_to :html, :json

  # GET /a/blog/posts
  # GET /a/blog/posts.json
  def index
    load_posts
  end

  # GET /a/blog/posts/new
  def new
    @post = Post.new
  end

  # GET /a/blog/posts/1/edit
  def edit
  end

  # POST /a/blog/posts
  # POST /a/blog/posts.json
  def create
    @post = Post.new(params[:post])
    flash[:notice] = "Post was successfully created." if @post.save
    respond_with @post, location: admin_posts_path

  end

  # PATCH/PUT /a/blog/posts/1
  # PATCH/PUT /a/blog/posts/1.json
  def update
    flash[:notice] = 'Post was successfully updated.' if @post.update(params[:post])
    respond_with @post, location: admin_posts_path
  end

  # DELETE /a/blog/posts/1
  # DELETE /a/blog/posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def load_post
    @post ||= post_scope.friendly.find(params[:id]).decorate
  end

  def load_posts
    query         = params[:search]
    page          = params[:page] || 1
    sort_order    = [sort_column, sort_direction].join(" ")
    @posts ||= post_scope.text_search(query).paginate(page: page, per_page: 20).reorder(sort_order).decorate
  end

  def post_scope
    Post.all
  end

  def sort_column
    sort      = params[:sort]
    Post.column_names.include?(sort) ? sort : "published_at"
  end

  def sort_direction
    direction = params[:direction]
    %w[asc desc].include?(direction) ? direction : "desc"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_tags, only: [:index, :show]

  # GET /blog/posts
  def index
    load_posts
  end

  # GET /blog/posts/1
  def show
    load_post
    @commentable = @post
    @comment = Comment.new
  end

  private

  def load_post
    @post = Post.friendly.find(params[:id]).decorate
  end

  def load_posts
    page = params[:page] || 1
    if params[:tag]
      set_tag
      posts = Post.tagged_with(@tag).paginate(page: page, per_page: 10).published.order("published_at desc")
    else
      posts = Post.paginate(page: page, per_page: 10).published.order("published_at desc")
    end
    @posts = PostDecorator.decorate_collection(posts)
  end

  def set_tag
    unclean_tag = (params[:tag].include? "-") ? params[:tag].gsub!('-', ' ') : params[:tag]
    @tag   = unclean_tag
  end

  def set_tags
    @tags = Post.tag_counts_on(:tags)
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def link_to_author(author)
    if author.gplus
      link_to "#{author.full_name}", "https://plus.google.com/#{author.gplus}?rel=author", target: "_blank"
    else
      "#{author.full_name}"
    end
  end



end

app/views/posts/_form.html.haml
- if post.errors.any?
  .alert.alert-block.alert-error
    %a.close{"data-dismiss" => "alert"} ×
    %h4.alert-heading Oh Snap!
    We found #{pluralize(post.errors.count, "problem")} with the form:
= f.input :title
= f.input :description, :as => :text, :input_html => {:class => 'span9', :rows => 5}
= f.input :abstract, :as => :text, :input_html => {:class => 'span9', :rows => 5}
= f.input :body, :as => :text, :input_html => {:class => 'span9', :rows => 30}
= f.input :tag_list, :hint => 'seperated by commas (example: foo, bar)'
= f.input :image, :as => :file, :label => "Upload an image."
= f.input :published_at, as: :datetime, required: true, ampm: true, order: [:month, :day, :year],  start_year: Time.now.year, end_year: Time.now.year - 6, default: Time.now.localtime
- if current_user.admin?
  = f.association :author, label_method: :full_name, value_method: :id, include_blank: false
- elsif current_user.author?
  = f.hidden_field :author_id, value: current_user.id
= f.input :is_commentable, :label => "Commentable?", :hint => "check to allow comments"

app/views/posts/_newsletter_signup.html.haml
.widget.newsletter.first
  .title
    %h3 Subscribe Now!
  .optin
    = render partial: "list_subscribers/form", locals: {list_subscriber: @list_subscriber}

app/views/posts/_post.html.haml
.post.post-summary
  - if post.image?
    .post-img.picture
      = link_to post_path(post) do
        = image_tag post.image.large
        .image-overlay-link
  / TODO: post icon should be moved to a helper
  %span.post-icon.standard
    %i.ico-pen.circle
  .post-content
    .post-title
      %h2= link_to post.title.titleize, post_path(post)
    .post-description
      = markdown_render(post.abstract)
    = link_to "Read More", post_path(post), class: "post-entry"
    .post-meta.clearfix
      %ul.post-meta-items.clearfix
        %li
          %i.mini-ico-user>
          By #{link_to_author(post.author)}
        %li
          %i.mini-ico-calendar>
          On #{post.published_at.strftime("%d %B, %Y")}
        - if post.is_commentable?
          %li
            %i.mini-ico-comment>
            With

            = link_to "#{post.comments.published.count} #{'comment'.pluralize(post.comments.count)}", post_path(post)
        - if post.tag_list.count > 0
          %li
            %i.mini-ico-tags
            = raw post.tag_list.map { |t| link_to t, tag_path(t.parameterize) }.join(', ')
        - if post.editable_by?(current_user)
          %li= link_to raw('<i class="icon-pencil"></i> Edit'), edit_admin_post_path(post), class: "btn btn-small"

app/views/posts/_tag_cloud.html.haml
.widget
  .title
    %h3 Tags
  .tags
    - tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
      = link_to tag.name, tag_path(tag.name.downcase.parameterize), class: "#{css_class}"

app/views/posts/index.html.haml
- content_for :title,  "Blog"

- content_for :content_top do
  #page-title.page-title-hero
    .hero-image.post-hero
    #page-title-inner
      .container
        %h1
          %i.ico-pencil
          Blog

.row
  .span8
    = render @posts
    %section= page_navigation_links(@posts)
  .span4
    = render "newsletter_signup"
    = render "tag_cloud"

app/views/posts/show.html.haml
- content_for :title,  @post.title
- content_for :description, @post.description
- content_for :og_url, request.original_url
- content_for :og_image, "#{image_url @post.image.medium}" if @post.image?
- content_for :meta_author, @post.author.full_name
- content_for :meta_twitter_creator, @post.author.twitter_handle

/ = render partial: "shared/page_title", locals: {title: @post.title, icon_class: "ico-pencil"}
- content_for :content_top do
  #page-title.page-title-hero
    .hero-image.post-hero{style: "background-image: url(#{@post.image.large});"}
    #page-title-inner
      .container
        %h1.text-center
          = @post.title
.row
  .span8
    .post.post-page
      .post-meta.clearfix
        %ul.post-meta-items.clearfix
          %li
            %i.mini-ico-user>
            By #{link_to_author(@post.author)}
          %li
            %i.mini-ico-calendar>
            On #{@post.published_at.strftime("%d %B, %Y")}
        .post-social.share-top
          .addthis_responsive_sharing
      %span.post-icon.standard
        %i.ico-pen.circle
      .post-content
        / .post-title
        /   %h2= @post.title.titleize
        .post-description
          = markdown_render(@post.body)
        .post-meta.clearfix
          .post-social.share-bottom
            .addthis_responsive_sharing
          %ul.post-meta-items.clearfix
            %li
              %i.mini-ico-user>
              By #{link_to_author(@post.author)}
            %li
              %i.mini-ico-calendar>
              On #{@post.published_at.strftime("%d %B, %Y")}
            - if @post.tag_list.count > 0
              %li
                %i.mini-ico-tags
                = raw @post.tag_list.map { |t| link_to t, tag_path(t.parameterize) }.join(', ')
            - if @post.editable_by?(current_user)
              %li= link_to raw('<i class="icon-pencil"></i> Edit'), edit_admin_post_path(@post), class: "btn btn-small"
    %hr/
    - if @post.is_commentable
      #comments
        .title-out
          %h3
            = 'Comment'.pluralize(@post.comments.published.count)
            %span.comments-amount
              (#{@post.comments.published.count})
        .comments
          = nested_comments @post.comments.published.arrange(order: "created_at asc")
        / .comments
        .clear
        %hr/
        .title-out
          %h3 Leave a Comment
        #comment_form_prime
          = render "comments/form"
  .span4
    = render "newsletter_signup"
    = render "tag_cloud"